#!/bin/bash
yum install fail2ban -y
systemctl enable fail2ban
cat <<EOF > /etc/fail2ban/jail.local
[DEFAULT]
# Ban hosts for 6 hour:
bantime = 21600
findtime = 600
maxretry = 3

# Override /etc/fail2ban/jail.d/00-firewalld.conf:
banaction = iptables-multiport

[sshd]
enabled = true
EOF
systemctl restart fail2ban
cat /etc/fail2ban/jail.local
fail2ban-client status sshd
echo "fail2ban-client status sshd" >> /root/.bashrc
