#!/bin/bash
# MARBEW.COM
#
#      
#
#      FROM ROOT USER, THE ONLY MANUAL THING TO DO IS:
#      vi restore.sh && chmod 700 restore.sh && ./restore.sh
#      
#      COPYING THE BELOW COMMENTED CODE IN restore.sh:
#
#      #!/bin/bash
#      yum update -y && \
#      yum install wget unzip -y && \
#      wget https://github.com/marbew/superbluecandy/archive/master.zip && \
#      unzip master.zip && \
#      cd superbluecandy-master/
#      chmod 700 redhat7_Lamp_restore 
#      ./redhat7_Lamp_restore
#      
#      
#
#run the script passing the right parameters for restoring the entire production website

echo -e "\n\n[1 OF 5] Enter USER@SERVER  backup_server: "
read server

echo -e "[2 OF 5] Enter /path_to_backup/uploadable.tar.gz backup_server: "
read uploadable

echo -e "[3 OF 5] Enter Mysql_password: "
read mysql_rootpwd

echo -e "[4 OF 5] Enter Database to import: "
read mysql_db_name

echo -e "[5 OF 5] Enter new Login User: "
read NEWUSER

timedatectl set-timezone UTC && \
yum install -y vim firewalld httpd mariadb-server mariadb php php-mysql mod_ssl mod_security wget sysstat mailx unzip && \
cd /tmp && \
wget https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm && \
rpm -Uvh epel-release-latest-7*.rpm && \
yum update -y && \
yum install -y tripwire arpwatch whois screen bind-utils mod_evasive && \
systemctl enable httpd mariadb arpwatch && \
systemctl restart firewalld httpd mariadb arpwatch && \
systemctl status firewalld httpd mariadb arpwatch && \
firewall-cmd --permanent --add-service=http && \
firewall-cmd --permanent --add-service=https && \
firewall-cmd --reload && \
#echo -e "\n[START COPYING PRIVATE KEY]"
cat <<EOF >> ~/.ssh/italia
-----BEGIN RSA PRIVATE KEY-----
MIIEpQIBAAKCAQEAxa3VfZf75Yf4CippMhOQvvpqHcNY0rU0DkIg/4c0l09wV4Yl
/qikxJ7BuJOY3RVG5SXJBPev6VBykjrizTYMamyPduz5t/qrbNVR7jrwcqhTDC6p
ckP1wUDvv1eYK5aQWXP+dN6JrgpqOMV79dEgpn9eU5eu/1HfvwQpBNJ+MfmqMNP4
l+KpJFMvUDtqv6Xzdaf/xR+9X9Rdum+ghQM4e0AM/ogkjt4Z7hSpOgZs5ccHL04O
u3uuh9gZY3ZcR2uayVoqecomeNtmwuR6QewdxWedxH6E/etBExnZF8ZI0g383vIN
anXC/vBIYEflmvk/u2U7FmGoTY9CJQWfB+bgYQIDAQABAoIBAA/tEWYs+H5llfY7
tH30VZUNV79OHbncH3WGnmH34qTOIZ7rj+QUcjHlGHZmbcpiDHQptyhPTDzf3lsp
o1wlHpr0ZBqQvQ21hFogVZl75iNWrFou6DfsgcAwGyCvTfM1DiwmzDleNHlxHV21
i2cikh7X5CGX9uFbF0usaiGZU9Fyx6PLV+CTQ0/xNiodTp9he0L5+96Br5lD5I0Y
UvRe1WLw6ELaLFF0DES2kN385ZBiyhAks0fPSyaqTQeu35gz1UkMWi7XUtI2ePRv
a45NOI0QdGQZTzKwn9+bEWQ01ZXO3IoPV1Uii1hrw0SMvWg0wUV1a6XVrXTKyA55
QOXejIECgYEA4hbD1RV1KPg2VwX+Ai/xIwOx4Ehm8Vkq1LO1NfuvtwqZ3VtJaOha
YvDWGhIHij3kKryKu/k2+ci/HbPVy0uym4vvdXJ8s4MVMO4l1YAxiD5+hqJGSWPu
ul2hBNdQLnD3tl4MD8rwtIFxSwHFEiT0Q/G9pbJ5t48++hrbZupdoUsCgYEA39Tg
QGkQOKWv8VdCakYBGSZ1ZziS4HDFkYMAO2Af1SLErFo0sDnkBOp9IACKWXp8uvLS
rCPjl8EpGEr6M4yfhNJIasnx1D4+r98zAfVHcJFVoDjUAA/pAgsM81E55Rya0O56
3mA0WsIxn3zD5RBKV5uPez6a+xithm1l+6YYpYMCgYEAlw820UyA91rAk+yBBt0Z
dJenZX96qI83Ot7HmMYNZXND0s6HgfydR7Y6lzisqQUpShSnbWjZ/pLOfv4FPsvZ
Dmy1FffksdxHcGXuCXSZo7p9t179L1QB0at1RlLGVAFOwR6dWH/zy+cg10jbb4AZ
ZLxERk21XZvsLBd9uImm/XkCgYEAsVXEEePrgSXsPoaGzRIHfriUnaIZ5A4UyZOD
lIc00TVJos+ZHOHQwQBTAA7NjdTYi3kk5lNM1wenmmKU1lCcdavwygKTQTfLjKWG
kQ+WeR38PAOqGx5/2imNKh15hAbktZGr8RFBiYJ/tD8yKQJ+E+jghaF1Qmkr2exE
t1rB/icCgYEAyWyd5KmoX94zyjF5fY2fR0elgELHd1/l1Tixuj2EMn+MhDCtusrf
BQq0C8o17GjUEUoJz7PK6dJZqTYqqXGkF7rCJfb04XfRB1yuCBAtaHbSDrOVBA15
ZylhsksWMVtA8UeTqkEnzhNfx0rDmx1BXRZJQ0BGXNKmKv/kshB4xl4=
-----END RSA PRIVATE KEY-----
EOF
#echo -e "\n[DONE!]\n"
chmod 400 ~/.ssh/italia

echo -e "\n[START COPYING ENTIRE BACKUP]"
ssh -i ~/.ssh/italia -o StrictHostKeyChecking=no $server -p 443 /opt/latest_backup
scp -r -i ~/.ssh/italia -P 443 $server:$uploadable /root/ && \
cd /root/ && \
tar -xzf /root/uploadable.tar.gz
echo -e "\n[DONE!]\n"
ls -la /root/
#echo -e "\n\n[DELETING TEMP FILE FROM BACKUP SERVER] "
ssh -i ~/.ssh/italia $server -p 443 rm -rf $uploadable
#echo -e "\n[DONE!]\n"
echo -e "\n\n[INSTALLING WORDPRESS UPDATED]"
cd /var/www/html && \
wget http://wordpress.org/latest.zip && \
unzip -q latest.zip && \
cp -r wordpress/* /var/www/html/ && \
echo -e "\n[DONE!]\n"
#echo -e "\n\n[COPY BACKUP WORDPRESS INTO NEW SERVER]"
cp /root/ec2-prod.marbew.com/my-backup/html/.htaccess /var/www/html/ 2>/dev/null
yes | cp /root/ec2-prod.marbew.com/my-backup/html/wp-config.php /var/www/html/wp-config.php 
cp -r /root/ec2-prod.marbew.com/my-backup/html/wp-content/uploads /var/www/html/wp-content/ 
cp -r /root/ec2-prod.marbew.com/my-backup/html/wp-content/plugins /var/www/html/wp-content/ 
cp -r /root/ec2-prod.marbew.com/my-backup/html/wp-content/themes/twentyfourteen /var/www/html/wp-content/themes/ 
yes | cp /root/ec2-prod.marbew.com/my-backup/root/.bashrc /root/ 2>/dev/null
cp /root/ec2-prod.marbew.com/my-backup/pki/tls/certs/2016-marbew.com.crt /etc/pki/tls/certs/ 
cp /root/ec2-prod.marbew.com/my-backup/pki/tls/certs/ca-marbew.com.crt /etc/pki/tls/certs/ 
cp /root/ec2-prod.marbew.com/my-backup/pki/tls/private/2016-marbew.com.key /etc/pki/tls/private/ 
cp /etc/httpd/conf.d/ssl.conf /etc/httpd/conf.d/ssl.conf.ori 
yes | cp /root/ec2-prod.marbew.com/my-backup/httpd/conf.d/ssl.conf /etc/httpd/conf.d/ 
yes | cp /root/ec2-prod.marbew.com/my-backup/httpd/conf.d/mod_security.conf /etc/httpd/conf.d/
yes | cp -r /root/ec2-prod.marbew.com/my-backup/root/* /root/
yes | cp -r /root/ec2-prod.marbew.com/my-backup/cron* /etc/
mkdir /my-backup
rm -rf /var/www/html/latest.zip
rm -rf /var/www/html/wordpress

#echo "[DECOMPRESS DATABASE]"
gzip -d < /root/ec2-prod.marbew.com/my-backup/mysql/$mysql_db_name > /root/ec2-prod.marbew.com/my-backup/mysql/db-sql
echo "[INSTALL DATABASE]"
mysql < /root/ec2-prod.marbew.com/my-backup/mysql/db-sql 
echo -e "\n[DONE!]\n"
systemctl restart httpd mariadb
systemctl status httpd mariadb
#echo "[READY TO GO] $(curl icanhazip.com)"
# add new user and block access to default one
useradd $NEWUSER
cd /home/ec2-user/
yes | cp -R .* /home/$NEWUSER/
yes | cp -R . /home/$NEWUSER/
cd /home/$NEWUSER
chown -R $NEWUSER:$NEWUSER *
chown -R $NEWUSER:$NEWUSER .*
echo "$NEWUSER           ALL=(ALL)       NOPASSWD: ALL" >> /etc/sudoers
usermod -s /sbin/nologin ec2-user
cd /root
rm -rf uploadable.tar.gz superbluecandy-master master.zip ec2-prod.marbew.com anaconda-ks.cfg
echo "[READY TO SSH IN WITH USER@SERVER: $NEWUSER@$(curl icanhazip.com)] "
echo "[REMEMBER TO MOUNT: /my-backup in /etc/fstab with new UUID] "
